<a href="https://colab.research.google.com/github/tanishqacodes/ASSIGNMENT-2/blob/main/26_FEB_ASS.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np
list_ = [ '1','2','3','4','5' ]
array_list = np.array(object = list_)

### Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code to print the data types of both the variables.

YES , there is difference in data type of list_ and array_list

In [4]:
type(list_)

list

In [5]:
type(array_list)

numpy.ndarray

### Q2. Write a code to print the data type of each and every element of both the variables list_ and arra_list.

In [6]:
print("LIST ")
for i in list_:
  print(i)

LIST 
1
2
3
4
5


In [7]:
print("ARRAY")
for i in array_list:
  print(i)

ARRAY
1
2
3
4
5


### Q3. Considering the following changes in the variable, array_list:

```
array_list = np.array(object = list_, dtype = int)
```

Will there be any difference in the data type of the elements present in both the variables, list_ and
arra_list? 
If so then print the data types of each and every element present in both the variables, list_
and arra_list.

Consider the below code to answer further questions:
```
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)
```

In [8]:
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)

In [9]:
type(num_list)

list

In [10]:
type(num_array)

numpy.ndarray

In [11]:
print('LIST')
for i in num_list:
  print(i)
print('ARRAY')
for i in num_array:
  print(i)

LIST
[1, 2, 3]
[4, 5, 6]
ARRAY
[1 2 3]
[4 5 6]


### Q4. Write a code to find the following characteristics of variable, num_array:
1. shape
2. size

In [12]:
import numpy as np
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(arr.shape)

(2, 4)


In [16]:
print(arr.size)

8


### Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array creation function.
[Hint: The size of the array will be 9 and the shape will be (3,3).]

In [17]:
zeros_array = np.zeros((3,3))
print(zeros_array)
print("Size : ",zeros_array.size)
print("Shape : ",zeros_array.shape)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Size :  9
Shape :  (3, 3)


### Q6. Create an identity matrix of shape (5,5) using numpy functions?
[Hint: An identity matrix is a matrix containing 1 diagonally and other elements will be 0.]

In [19]:
identity_matrix = np.eye(5)
print(identity_matrix)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
